//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace REDOXEntities.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public int ID { get; set; }
        public string PUB_DT_STR { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public double SQ { get; set; }
        public bool DISABLE { get; set; }
        public bool HOME_PAGE_DISPLAY { get; set; }
        public Nullable<System.DateTime> BUD_DT { get; set; }
        public int BUD_ID { get; set; }
        public System.DateTime UPT_DT { get; set; }
        public int UPT_ID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
