//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace REDOXEntities.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string SPEC { get; set; }
        public string DESC { get; set; }
        public string HOME_INFO { get; set; }
        public string CONTENT { get; set; }
        public double SQ { get; set; }
        public bool DISABLE { get; set; }
        public bool HOME_PAGE_DISPLAY { get; set; }
        public System.DateTime BUD_DT { get; set; }
        public int BUD_ID { get; set; }
        public System.DateTime UPT_DT { get; set; }
        public int UPT_ID { get; set; }
        public string EDIT1 { get; set; }
        public string EDIT1_MOBILE { get; set; }
        public string EDIT2 { get; set; }
        public string EDIT2_MOBILE { get; set; }
        public string EDIT3 { get; set; }
        public string EDIT3_MOBILE { get; set; }
        public string QA { get; set; }
    }
}
